### ISSUE TITLE
AlarmManager does not work when replicated

### ISSUE THREAD

**Issue by theflopguy** [learntodroid/SimpleAlarmClock#1]
Hi, I have cloned this repository to run using Android Studio on my phone running Android P, It worked perfectly fine.

However, when I try to run an app that I have created using the same logic. I am not Receiving the broadcast once the application is removed off the "Recent Apps" list. 

Is there anything you've done programmatically to ensure this or is there any trick to getting this to work?

I would very much appreciate the help.

**Comment by learntodroid** [comment]
Sorry, you are facing this issue. If I understand you correctly you are not experiencing this issue with my Simple Alarm Clock app but with the app, you have created. Any chance you can share your code with me? Happy to clone your code repo and try and find the issue.

I would also recommend reading the following post on learntodroid.com if you haven't already.

https://learntodroid.com/how-to-create-a-simple-alarm-clock-app-in-android/

**Comment by learntodroid** [comment]
Something I found weird when using the emulator from Android Studio.

If I use the green play button to start the app, then I schedule an alarm and remove the app from the recent apps list the scheduled alarm won't start.

But if I launch the app by selecting the app icon in the emulator, then schedule an alarm then remove the app from the recent apps list the scheduled alarm will start.

This appears to be a bug with the emulator.
