### ISSUE TITLE
Bug in Alarm.java

### ISSUE THREAD

**Issue by excellentiam-prog** [learntodroid/SimpleAlarmClock#2]
First of all, I would like to express my gratitude for the alarm clock on Github. 

I noticed when I schedule a new alarm selecting a day, Friday, for example, the toast shows Monday.

The toast is in Alarm.java and using "DayUtil.toDay(calendar.get(Calendar.DAY_OF_WEEK)" to get the scheduled day.

regards

![Screenshot_2020-08-09-11-39-21-827_com learntodroid simplealarmclock](https://user-images.githubusercontent.com/66888451/89734918-5278ed00-da35-11ea-91bb-d20eb76470f1.jpg)
![Screenshot_2020-08-09-11-39-25-761_com learntodroid simplealarmclock](https://user-images.githubusercontent.com/66888451/89734923-56a50a80-da35-11ea-9a84-2d5d10a6e507.jpg)

**Comment by learntodroid** [comment]
Thanks for raising this issue. Appreciate the effort you took to share this bug. I will fix this shortly and merge the changes into the master branch and make sure the tutorial is updated to reflect the change.

**Comment by learntodroid** [comment]
closing this issue, pull request with the fix has been merged into master
