### ISSUE TITLE
Bug with the Switch

### ISSUE THREAD

**Issue by excellentiam-prog** [learntodroid/SimpleAlarmClock#4]
Dear mates, 
I want to collaborate showing a problem I found, to improve the SimpleAlarm project.

I found a bug with the Switch. Unfortunately, I don't know the pattern that is beginning to emerge, but I tried several times and at some point, the switches are "entangled". As I increase the number of alarms at different times and sometimes using "recurring", the problem arises. Maybe the position of the fragment at the list or the hour... I don't know. 

I tried to upload a video, but the GitHub didn't allow the format, so I put it on google drive:
https://drive.google.com/drive/folders/136bYI89wSfLzIS79ofgaWODZvPzKzfNY?usp=sharing

Regards

**Comment by excellentiam-prog** [comment]
I did more tests and I found the issue starts when adding the sixth alarm. I added two screen recording

**Comment by learntodroid** [comment]
thanks for raising this issue, i will investigate this and get back to you with a fix.

**Comment by learntodroid** [comment]
Thanks for raising this bug. I have located the issue. There was a defect in the RecyclerView adapter class. Now when views in the RecyclerView are recycled I will override the onCheckChanged listener for the switches in the RecyclerView to null.
