### ISSUE TITLE
Bug after the ring

### ISSUE THREAD

**Issue by excellentiam-prog** [learntodroid/SimpleAlarmClock#5]
Dear, 

I found a bug. If I schedule an alarm for 5 minutes, for example, and it works nicely. However, if I schedule others after the first ring, can be one alarm or several, no matter the time, none will work anymore. I tried dozens of times. 

The inclusion of a new alarm after a ring disrupts all alarms.

It only fires when I reopen the app, at the wrong time. 

I did three screen recorders. They are in the google drive folder

I put 2 videos where the inclusion of the alarm doesn't work after the first fires, and another video that I schedule 2 alarms in a row with a minute of difference, then I include a new one after the first ring. The new alarm and the remaining one don't work.

https://drive.google.com/drive/folders/1WR4U47lM1vrHW9cCInHnw_7mEW_ZBBFa?usp=sharing
..

**Comment by excellentiam-prog** [comment]
Another issue. Only now I realize the alarm doesn't fire after rebooting the smartphone. I would appreciate feedback if is only me, please

**Comment by learntodroid** [comment]
Hello unfortunately when the app is forced closed, the alarms will be canceled and will not be restored when the app gets reopened unless done manually by the user. This is a limitation with AlarmManager.

See https://stackoverflow.com/questions/14041208/how-to-reset-alarm-if-app-is-force-closed-in-android?noredirect=1&lq=1

However, if you reboot your device without the app being forced closed first, the alarms should still work without requiring recreation. I have tested this in the emulator and it is working for me.

**Comment by potipone** [comment]
How I can delete scheduled alarms ?
